<a href="https://colab.research.google.com/github/HyosangKwon/Data-analysis-to-study-alone-with-python-/blob/main/03_2_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%95%EC%A0%9C(%EC%9E%98%EB%AA%BB%EB%90%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A0%95)ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

># 데이터프레임 정보 요약하기

In [1]:
import gdown
gdown.download('https://bit.ly/3GisL6J', 'ns_book4.csv', quiet=False)

Downloading...
From: https://bit.ly/3GisL6J
To: /content/ns_book4.csv
100%|██████████| 55.5M/55.5M [00:02<00:00, 22.1MB/s]

'ns_book4.csv'

In [2]:
import pandas as pd
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0.0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0.0,2021-03-19

In [3]:
# info() 사용하여 NaN 아닌 값 몇개인지 확인
ns_book4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384591 entries, 0 to 384590
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       384591 non-null  int64
 1   도서명      384188 non-null  object
 2   저자       384393 non-null  object
 3   출판사      379950 non-null  object
 4   발행년도     384577 non-null  object
 5   ISBN     384591 non-null  object
 6   세트 ISBN  56576 non-null   object
 7   부가기호     310386 non-null  object
 8   권        63378 non-null   object
 9   주제분류번호   364727 non-null  object
 10  도서권수     384591 non-null  int64
 11  대출건수     384591 non-null  float64
 12  등록일자     384591 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 38.1+ MB

># 누락된 값 처리하기
- 누락된 값이 정확히 몇개가 있는지 확인하고 표시한다.
- 누락된 값을 다른 값으로 바꾼다.

>>## 누락된 값 개수 확인하기: `isna()`
- `isna()` 메서드는 각 행이 비어있는지를 나타내는 불리언 배열을 반환
- `sum()` 메서드를 이어서 호출하면 불리언 배열의 True 개수로 비어있는 행 개수를 얻을 수 있음

In [4]:
ns_book4.isna().sum()

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN    328015
부가기호        74205
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [5]:
# 누락되지 않은 값을 확일할 때는 notna() 메서드 사용
ns_book4.notna().sum()

번호         384591
도서명        384188
저자         384393
출판사        379950
발행년도       384577
ISBN       384591
세트 ISBN     56576
부가기호       310386
권           63378
주제분류번호     364727
도서권수       384591
대출건수       384591
등록일자       384591
dtype: int64

>>## 누락된 값으로 표시하기: None 과 np.nan

In [6]:
# ns_book4 데이터프레임의 '도서권수' 열에 있는 첫 번째 행 값을 None으로 바꾼 후 '도서권수'열에 isna() 메서드를 적용해 누락된 값을 세어보기

ns_book4.loc[0, '도서권수'] = None
ns_book4['도서권수'].isna().sum()

1

In [7]:
ns_book4.head(2)
# NaN을 실수로 저장하기 때문에 도서권수가 정수에서 실수형으로 변경됨.

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,NaN,0.0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1.0,0.0,2021-03-19

In [8]:
# '도서권수' 첫 번째 행 원래대로 바꾸기, 데이터 타입도 원래대로 변경

ns_book4.loc[0, '도서권수'] = 1
ns_book4 = ns_book4.astype({'도서권수': 'int32', '대출건수' : 'int32'}) # 매개변수를 딕셔너리 형식으로 전달
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [9]:
# 문자열 형식 열에 None 입력
import numpy as np
ns_book4.loc[0, '부가기호'] = np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19

>>## 누락된 값 바꾸기(1): loc,fillna() 메서드

In [10]:
# 세트 ISBN 열의 누락된 값을 빈 문자열(' ') 로 변경
# 누락된 값을 가리키는 불리언 배열을 isna() 메서드로 만들어 loc 메서드에 전달

set_isbn_na_rows = ns_book4['세트 ISBN'].isna() # 누락된 값 불리언 배열 반환
ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''
ns_book4['세트 ISBN'].isna().sum()

0

In [11]:
# fillna()는 새로운 데이터프레임을 반환
ns_book4.fillna('없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [12]:
# 특정 열만 선택하여 NaN 바꾸기

ns_book4['부가기호'].fillna('없음').isna().sum()

0

In [13]:
# '부가기호' 열의 NaN을 바꾸면서 전체 데이터프레임 반환

ns_book4.fillna({'부가기호':'없음'}).isna().sum() # 열 이름과 바꾸려는 값으로 이루어진 딕셔너리 전달

번호              0
도서명           403
저자            198
출판사          4641
발행년도           14
ISBN            0
세트 ISBN         0
부가기호            0
권          321213
주제분류번호      19864
도서권수            0
대출건수            0
등록일자            0
dtype: int64

>>## 누락된 값 바꾸기(2): `replace()`
- replace(원래 값, 새로운 값) : 바꾸려는 값 하나일 때
- replace([원래 값1, 원래값2],[새로운 값1, 새로운 값2]) : 여러개일 때
- replace({열 이름: 원래 값}, 새로운 값) : 열 마다 다른 값으로 바꿀 때

In [14]:
ns_book4.replace(np.nan, '없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [15]:
# 바꾸려는 값 여러개
ns_book4.replace([np.nan, '2021'],['없음',21]).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,없음,없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,없음,없음,1,0,2021-03-19

In [16]:
# 딕셔너리 형식으로도 전달 가능
ns_book4.replace({np.nan:'없음', '2021':21}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,없음,없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,없음,없음,1,0,2021-03-19

In [17]:
# 열 마다 다른 값으로 바꿀 때

ns_book4.replace({'부가기호':np.nan},'없음').head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,없음,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,없음,NaN,NaN,1,0,2021-03-19

In [18]:
ns_book4.replace({'부가기호': {np.nan: '없음'}, '발행년도': {'2021': '21'}}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,21,9788937444319,,없음,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,21,9791190123969,,없음,NaN,NaN,1,0,2021-03-19

-----------
># 정규표현식

In [19]:
ns_book4.replace({'발행년도': {'2021': '21'}})[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,2018,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

In [20]:
# 위와 동일
ns_temp = ns_book4.replace({'발행년도':{'2021':'21'}})
ns_temp[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,2018,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

>>## 숫차 찾기: \d
- 정규표현식 숫자 표현: \d
- 연도 표현: \d\d\d\d
- 뒤에 두자리 묶기: \d\d(\d\d)

In [21]:
# 정규표현식 사용시 regex 매개변수 사용

ns_book4.replace({'발행년도': {r'\d\d(\d\d)': r'\1'}}, regex=True)[100:102]

# r 문자는 파이썬에서 정규 표현식을 다른 문자열과 구분하기 위해 접두사처럼 붙임

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

In [22]:
# 정규표현식 반복시 중괄호를 사용하여 개수지정 가능

ns_book4.replace({'발행년도': {r'\d{2}(\d{2})': r'\1'}}, regex = True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드 (지은이), 김진웅 (옮긴이)",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아 (지은이), 안기순 (옮긴이)",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

>>## 문자 찾기: 마침표(.)
- 어떤 문자에도 대응하는 정규표현식은 (.)이다.
- *를 사용하여 0개 이상 반복된다고 표시할 수 있다.
- 괄호()를 일반 문자로 인식하게 하려면 역슬래시를 앞에 붙여 쓴다. `\(\)`

In [23]:
ns_book4.replace({'저자': {r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)': r'\1\2'}, '발행년도':{r'\d{2}(\d{2})': r'\1'}}, regex=True)[100:102]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
100,101,No라고 말할 줄 아는 남편과 아내 - 개정판,"헨리 클라우드, 존 타운센드, 김진웅",좋은씨앗,18,9788958743019,,NaN,NaN,234.9,1,1,2021-03-15
101,102,"D2C 레볼루션 - 스타트업부터 글로벌 기업까지, 마켓 체인저의 필수 전략","로런스 인그래시아, 안기순",부키,21,9788960518483,,NaN,NaN,325.1,1,0,2021-03-15

---------
># 잘못된 값 바꾸기

In [24]:
# '발행년도' 열을 int32로 바꾸기
ns_book4.astype({'발행년도': 'int32'})

ValueError: ignored

In [25]:
# '1988.' 연도를 변환할 수 없어 오류가 발생.

ns_book4['발행년도'].str.contains('1988').sum() # '발행년도' 열에 '1988'이 포함된 행의 개수 세기

407

In [26]:
# '발행년도' 열에서 숫자가 아닌 문자를 포함하는 모든 행 찾아보기
# na 매개변수 True로 지정하여 누락된 행을 True로 표시

invalid_number = ns_book4['발행년도'].str.contains('\D', na=True)
print(invalid_number.sum()) # 숫자 이외의 문자가 들어간 행의 개수를 출력
ns_book4[invalid_number].head()

1777

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988.,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,단기4334[2001],9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,[2019],9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019.,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018.,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [27]:
# 정규 표현식을 사용하여 연도 앞과 뒤에 있는 문자를 제외

ns_book5 = ns_book4.replace({'발행년도':'.*(\d{4}).*'}, r'\1', regex = True)
ns_book5[invalid_number].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
19138,19565,단국강토,홍태수 저,매일경제신문사,1988,9788974420031,,NaN,NaN,511.1,1,1,2019-12-19
19227,19736,삼성의 역사,송부웅 撰,삼양,2001,9788985464369,,0,NaN,911.02,1,1,2019-12-06
26097,26812,배고픈 애벌레,에릭 칼 글·그림 ;이희재 옮김,더큰컴퍼니,2019,9788959514083,,NaN,NaN,843,1,0,2019-08-12
29817,30586,(The) Sopranos sessions,"Matt Zoller Seitz,$eAlan Sepinwall,$eLaura Lip...",Harry N Abrams Inc,2019,9781419734946,,NaN,NaN,326.76,1,0,2019-06-13
29940,30709,다음엔 너야,에른스트 얀들 글;노르만 융에 그림;박상순 옮김,비룡소,2018,9788949110646,9788949110004,7,NaN,853,1,9,2019-06-04

In [28]:
# 다시 숫자 이외의 문자가 들어간 행의 개수와 데이터를 확인

unknown_year = ns_book5['발행년도'].str.contains('\D', na = True)
print(unknown_year.sum())
ns_book5[unknown_year].head()

67

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
30838,31616,본격 한중일 세계사 5,굽시니스트 지음,위즈덤하우스,NaN,9791190065092,,NaN,NaN,NaN,0,0,2019-05-28
39130,40141,정책금융의 현황과 발전과제,정책금융연구회,한국산업은행,NaN,9788992784108,,NaN,NaN,327.1,1,0,2019-01-22
39256,40268,서울지역 유적 발굴조사 총서 3,서울역사박물관,서울역사박물관,NaN,9791186324714,9791186324431,NaN,NaN,NaN,0,0,2019-01-22
76836,81202,흰머리 큰줄기,한호진 지음,秀文出版社,[발행년불명],9788973010769,,0,NaN,699.1,1,1,2016-11-10
150543,160436,(속) 경제학사,박장환 지음,NaN,[20--],9788994339207,,1,NaN,320.9,1,2,2012-11-19

In [29]:
# 변환되지 않은 값은 NaN이거나 네 자리 숫자가 아닌 값들이다.
# 임의로 -1로 바꾼 다음 astype() 메서드의 '발행년도'열의 데이터 타입을 정수형인 int32로 변환한다.

ns_book5.loc[unknown_year, '발행년도'] = '-1'
ns_book5 = ns_book5.astype({'발행년도':'int32'})

In [30]:
# 연도 중 아주 큰 값이나 작은 값이 들어있는 경우를 확인
# 연도가 4000년이 넘는 경우 확인해보기

ns_book5['발행년도'].gt(4000).sum() # 연도가 4000년이 넘는 행의 전체 개수 확인

131

In [31]:
# 위와 동일
(ns_book5['발행년도']>4000).sum()

131

In [32]:
# 4000년이 넘는 연도에서 2333을 빼서 서기로 바꾼 다음 연도가 4000년이 넘는 도서가 있는지 확인

dangun_yy_rows = ns_book5['발행년도'].gt(4000) # 4000보다 큰 값을 찾는다.
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333 # 찾은 값에서 2333을 빼서 서기로 바꿈

dangun_year = ns_book5['발행년도'].gt(4000) # 다시 4000보다 큰 값 찾기
print(dangun_year.sum())
ns_book5[dangun_year].head()

13

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
222858,234268,Modern art,[computer file],GROLIER,7611,9780717233243,,NaN,NaN,609.205,1,1,2009-05-07
270269,282852,현대 영어학=Linguistic theory in modern english,이재영,열림기획,7634,9788986705072,,1,NaN,740.1,1,6,2007-04-14
352000,367380,비는 어디서 왔을까?,김순한 글,웅진닷컴,5167,9788901038117,,7,NaN,453.77,1,7,2004-10-28
366958,383152,Wines of the world,NaN,Multicom Publishing,7600,9781884014062,,NaN,NaN,573.2,1,0,1970-01-01
366959,383153,The greatest children's stories ever told,NaN,QUEUE,7622,9781564348548,,NaN,NaN,843,1,0,1970-01-01

In [33]:
# 연도가 비정상적으로 높은 도서는 13권, 모두 -1로 표시하기

ns_book5.loc[dangun_year, '발행년도'] = -1

In [34]:
# 마지막으로 연도가 작은 값도 확인 / 0보다 크고 1900년도 이전의 도서 찾아보기

old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900) # lt 는 1900보다 작은 값 찾기

ns_book5[old_books]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
61149,64093,"고흐 씨, 시 읽어 줄까요 :내 마음을 알아주는 시와 그림의 만남",이운진 지음,사계절,176,9788958284277,,0,NaN,811.7,1,6,2017-10-27
70566,74347,정신 병리학의 문제들,지은이: 지그문트 프로이트 ;옮긴이: 황보석,열린책들,151,9788932905181,9788932905082,9,10,185.5,1,4,2017-04-26
79550,84164,(최근 7년간) 중요 민법판례 :[2009년 1월~2016년 6월 중요 판례],이광섭 편저,법학사,163,9788962898651,,9,NaN,365,1,14,2016-09-27
147950,157759,(한·중·일) 밥상 문화 :대표음식으로 본 3국 문화비교,김경은 지음,이가서,132,9788958643012,,0,NaN,381.75,1,30,2013-02-19
194576,205407,책으로 뒤덮인 집의 비밀,N.E. 보드 지음 ;피터 퍼거슨 그림 ;김지현 옮김,개암나무,1015,9788992844413,,7,NaN,843,1,15,2010-08-18
287252,300283,(밝혀질)우리歷史,吳在城 著,黎民族史硏究會,1607,9788986892130,,0,NaN,911,1,5,2006-07-06

In [35]:
ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum() # -1과 같은 값이 몇 개인지 센다.

86

># 누락된 정보 채우기

In [36]:
# 발행년도가 -1 즉, 잘못 저장되어 있거나 알 수 없는 경우 채워줘야 함.
# '도서명', '저자', '출판사' 열에 누락된 값이 있거나 '발행년도'열이 -1인 행의 개수 확인

na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)

print(na_rows.sum())

ns_book5[na_rows].head()

5268

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
78,79,아산 정주영 레거시,김화진,NaN,2021,9788952129529,,NaN,NaN,325,1,1,2021-03-15
265,278,골목의 시간을 그리다,정명섭.김효찬 지음,NaN,2021,9791191266054,,NaN,NaN,NaN,1,0,2021-03-12
354,367,한국인의 맛,정명섭 지음,NaN,2021,9791155401804,,NaN,NaN,NaN,1,0,2021-03-12
539,552,"한성부, 달 밝은 밤에",김이삭 지음,NaN,2021,9791163161479,,NaN,NaN,NaN,1,0,2021-03-12
607,620,100일 완성 마그마 러시아어 중고급 단어장,러포자 구제 연구소 외 지음,NaN,2021,9788974829193,,NaN,NaN,NaN,1,0,2021-03-12

In [37]:
# 뷰티풀수프를 활용해 값 채우기

import requests
from bs4 import BeautifulSoup

# Yes24 에서 ISBN으로 검색한 결과 페이지에서 개발자 도구로 도서명 태그 정보 확인
# <a> 태그에 원하는 정보가 들어 있음을 확인할 수 있음

# 도서명을 가져오는 함수 작성

def get_book_title(isbn):
    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

    # URL에 ISBN을 넣어 HTML 가져옴
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser') # HTML 파싱

    # 클래스 이름이 'gd_name'인 <a> 태그의 텍스트를 가져옴.
    title = soup.find('a', attrs={'class':'gd_name'}).get_text()

    return title

In [38]:
# '골목의 시간을 그리다'책의 ISBN으로 테스트

get_book_title(9791191266054)

'골목의 시간을 그리다'

In [39]:
# 마찬가지로 다른 정보들도 추출하여 반환
# 저자는 두 명 이상일 수 있기 때문에 find_all() 메서드를 사용해 저자를 담은 <a> 태그를 모두 추출

import re # re 모듈의 findall() 사용하면 정규식에 매칭되는 모든 문자열을 찾아 리스트로 반환

def get_book_info(row):
    title = row['도서명']
    author = row['저자']
    pub = row['출판사']
    year = row['발행년도']

    # Yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

    # URL에 ISBN을 넣어 HTML 가져옴
    r = requests.get(url.format(row['ISBN']))
    soup = BeautifulSoup(r.text, 'html.parser') # HTML 파싱

    try:
        if pd.isna(title): # 도서명 비어 있는 경우
            # 클래스 이름이 'gd_name'인 <a> 태그의 텍스트를 가져온다.
            title = soup.find('a', attrs={'class':'gd_name'}).get_text()

    except AttributeError:
        pass

    try:
        if pd.isna(author):
            # 클래스 이름이 'info_auth'인 <span> 태그 아래 <a> 태그의 텍스트를 가져옴
            authors = soup.find('span', attrs={'class':'info_auth'}).find_all('a')
            author_list = [auth.get_text() for auth in authors]
            author = ','.join(author_list)

    except AttributeError:
        pass


    try:
        if pd.isna(pub):
            # 클래스 이름이 'info_auth'인 <span> 태그 아래 <a> 태그의 텍스트를 가져옴

            pub = soup.find('span', attrs={'class':'info_pub'}).find('a').get_text()

    except AttributeError:
        pass


    try:
        if year == -1:
            # 클래스 이름이 'info_date'인 <span> 태그 아래 텍스트를 가져옴
            year_str = soup.find('span', attrs = {'class':'info_date'}).get_text()

            # 정규 표현식으로 찾은 값 중에 첫 번째 것만 사용
            year = re.findall(r'\d{4}', year_str)[0]

    except AttributeError:
        pass

    return title, author,pub,year

In [40]:
# apply() 메서드는 기본적으로 반환된 값을 하나의 튜플로 만듬. result_type 매개변수를 'expand'로 지정하여 반환된 값을 각기 다른 열로 만들 수 있다.

updated_sample = ns_book5[na_rows].head(2).apply(get_book_info, axis=1, result_type = 'expand')
updated_sample

               0           1           2     3
78    아산 정주영 레거시         김화진  서울대학교출판문화원  2021
265  골목의 시간을 그리다  정명섭.김효찬 지음      초록비책공방  2021

In [41]:
# 모든 행에 적용할 수 있지만 시간 너무 오래걸림. 미리 만들어 놓은 데이터 프레임 다운

gdown.download('https://bit.ly/3UJZiHw', 'ns_book5_update.csv', quiet=False)
ns_book5_update = pd.read_csv('ns_book5_update.csv', index_col=0)
ns_book5_update.head()

Downloading...
From: https://bit.ly/3UJZiHw
To: /content/ns_book5_update.csv
100%|██████████| 406k/406k [00:00<00:00, 16.2MB/s]

                          도서명               저자         출판사  발행년도
78                 아산 정주영 레거시              김화진  서울대학교출판문화원  2021
265               골목의 시간을 그리다       정명섭.김효찬 지음      초록비책공방  2021
354                    한국인의 맛           정명섭 지음         추수밭  2021
539              한성부, 달 밝은 밤에           김이삭 지음      고즈넉이엔티  2021
607  100일 완성 마그마 러시아어 중고급 단어장  러포자 구제 연구소 외 지음         문예림  2021

In [42]:
# ns_book5 데이터프레임을 ns_book5_update 데이터프레임 데이터로 업데이트 후 누락된 행 확인

ns_book5.update(ns_book5_update)
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna()| ns_book5['출판사'].isna() | ns_book5['발행년도'].eq(-1)
print(na_rows.sum())

4615

In [43]:
# 마지막으로 누락된 값을 가진 행을 삭제하여 분석 대상에서 제외

ns_book5 = ns_book5.astype({'발행년도': 'int32'})
ns_book6 = ns_book5.dropna(subset=['도서명','저자','출판사'])
ns_book6 = ns_book6[ns_book6['발행년도'] != -1]
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,,NaN,NaN,NaN,1,0,2021-03-19

In [44]:
# 데이터프레임 저장
ns_book6.to_csv('ns_book6.csv', index=False)